# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3

      - name: UPX GitHub Action
        uses: crazy-max/ghaction-upx@v1.4.0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile "Amplitude Custom Suite.py"
          mkdir dist\temp
          xcopy executables dist\executables\ /E
          copy LICENSE dist\
          copy README.md dist\
          xcopy silence dist\silence\ /E

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.0.0
        with:
          # Artifact name
          name: "Amplitude Custom Suite"
          # A file, directory or wildcard pattern that describes what to upload
          path: 'dist\*'
